openapi: 3.0.0

info:
  title: primality-test-swagger-example
  version: 0.0.1

servers:
  - url: https://endpoint.ainize.ai/kiyeopyang/webapp/

paths:
  /:
    get:
      responses:
        "200":
          content:
            applicatioin/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        "400":
          description: Bad Request Error
        default:
          description: Unexpected Error
